server:
  # [修复警告] server.host/port 已废弃，改用 address
  address: "tcp://0.0.0.0:9091"

identity_validation:
  reset_password:
    # [修复警告] jwt_secret 移动到了这里
    # 记得替换为随机长字符串
    jwt_secret: "generate_a_secure_random_string_here_for_jwt"


log:
  level: info

# 认证后端：这里使用本地文件，也可以配置 LDAP
authentication_backend:
  file:
    path: /config/users_database.yml

# 访问控制策略
access_control:
  default_policy: deny
  rules:
    - domain: "fyp-app.hogwarts.ac"
      policy: one_factor

# 会话存储 (连接到 Docker 中的 Redis)
session:
  name: authelia_session
  redis:
    host: ACT-auth-system-redis
    port: 6379
  cookies:
    - domain: example.com
      authelia_url: https://app.example.com
      default_redirection_url: https://www.example.com

# 存储后端 (连接到 Docker 中的 Postgres)
storage:
  postgres:
    host: ACT-auth-system-postgres
    port: 5432
    database: authelia
    username: authelia
  encryption_key: "QzpEHmQQEAwEqCKOSnWQd3ibg6x11fCViRzoY6kqzlmVlxQ0ugIsnzHFf9PR7iVx"

# 通知方式 (用于发送重置密码邮件等)
notifier:
  filesystem:
    filename: /config/notification.txt
  # 生产环境请配置 SMTP:
  # smtp:
  #   host: smtp.gmail.com
  #   port: 587
  #   username: your_email@gmail.com